plugins {
    id 'com.android.application'
}

def ciVersionCode = (System.getenv("GITHUB_RUN_NUMBER") ?: "5").toInteger()

android {
    namespace 'com.nateghi.vocabflashcards'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nateghi.vocabflashcards.phase1'
        minSdk 24
        targetSdk 35
        versionCode ciVersionCode
        versionName "3.0.${ciVersionCode}"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
